# Generated by Django 5.1.7 on 2025-04-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_certificate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtask',
            name='file_path',
        ),
        migrations.AddField(
            model_name='completedtask',
            name='answer',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='completedtask',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
