# Generated by Django 5.1.7 on 2025-04-14 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_task_extra_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.section'),
        ),
    ]
