# Generated by Django 5.1.7 on 2025-04-15 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_task_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.program'),
        ),
    ]
