# Generated by Django 5.1.7 on 2025-04-15 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_participant_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.program'),
            preserve_default=False,
        ),
    ]
